import type { Flight } from './types'

const base = {
  departureDate: '2026-10-14',
  arrivalDate: '2026-10-14',
  bookingHours: 24,
  refundConditions: 'Возврат доступен онлайн по правилам тарифа. Возможны удержания авиакомпании.',
  priceCheckedMinutesAgo: 5,
} as const

export const mockFlights: Flight[] = [
  { ...base, id: 'su-1883', airline: 'Аэрофлот', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Шереметьево SVO', departureTime: '06:20', arrivalTime: '08:55', durationMinutes: 275, stops: 0, baggage: true, priceRUB: 17840, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 4, recommended: true, departurePeriod: 'morning' },
  { ...base, id: 'y7-905', airline: 'Nordwind', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Шереметьево SVO', departureTime: '11:35', arrivalTime: '14:20', durationMinutes: 285, stops: 0, baggage: false, priceRUB: 14220, freeBooking: false, bookingHours: 0, refundable: false, refundConditions: 'Тариф невозвратный. Вернутся только предусмотренные правилами сборы.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 7, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 9 },
  { ...base, id: 'u6-1802', airline: 'Уральские авиалинии', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Домодедово DME', departureTime: '17:15', arrivalTime: '20:05', durationMinutes: 290, stops: 0, baggage: true, priceRUB: 19490, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный. Условия вынужденного возврата зависят от авиакомпании.', flexibleDate: true, kyrgyzCardsSupported: false, seatsLeft: 3, recommended: false, departurePeriod: 'evening', priceCheckedMinutesAgo: 12 },
  { ...base, id: 's7-3012', airline: 'S7 Airlines', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Домодедово DME', departureTime: '23:40', arrivalTime: '05:55', arrivalDate: '2026-10-15', durationMinutes: 495, stops: 1, baggage: true, priceRUB: 16980, freeBooking: false, bookingHours: 0, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 6, recommended: false, departurePeriod: 'night', priceCheckedMinutesAgo: 7, priceChanged: true },
  { ...base, id: 'su-1899', airline: 'Аэрофлот', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Шереметьево SVO', departureTime: '05:45', arrivalTime: '08:30', durationMinutes: 285, stops: 0, baggage: true, priceRUB: 18520, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 5, recommended: true, departurePeriod: 'morning', priceCheckedMinutesAgo: 4 },
  { ...base, id: 'dp-934', airline: 'Победа', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Внуково VKO', departureTime: '14:10', arrivalTime: '17:05', durationMinutes: 295, stops: 0, baggage: false, priceRUB: 13670, freeBooking: false, bookingHours: 0, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 2, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 10 },
  { ...base, id: 'u6-2810', airline: 'Уральские авиалинии', departureCity: 'Бишкек', arrivalCity: 'Краснодар', departureAirport: 'Манас FRU', arrivalAirport: 'Пашковский KRR', departureTime: '08:25', arrivalTime: '15:10', durationMinutes: 525, stops: 1, baggage: true, priceRUB: 21450, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 8, recommended: true, departurePeriod: 'morning', priceCheckedMinutesAgo: 6 },
  { ...base, id: 's7-3490', airline: 'S7 Airlines', departureCity: 'Бишкек', arrivalCity: 'Екатеринбург', departureAirport: 'Манас FRU', arrivalAirport: 'Кольцово SVX', departureTime: '19:35', arrivalTime: '22:35', durationMinutes: 180, stops: 0, baggage: true, priceRUB: 15890, freeBooking: false, bookingHours: 0, refundable: true, flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 9, recommended: true, departurePeriod: 'evening', priceCheckedMinutesAgo: 8 },
  { ...base, id: 'n4-507', airline: 'Nordwind', departureCity: 'Бишкек', arrivalCity: 'Екатеринбург', departureAirport: 'Манас FRU', arrivalAirport: 'Кольцово SVX', departureTime: '02:40', arrivalTime: '10:25', durationMinutes: 465, stops: 1, baggage: false, priceRUB: 12990, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: true, kyrgyzCardsSupported: false, seatsLeft: 4, recommended: false, departurePeriod: 'night', priceCheckedMinutesAgo: 14 },
]

export const airlines = [...new Set(mockFlights.map((flight) => flight.airline))]
