import type { Flight } from './types'

const base = {
  departureDate: '2026-10-14',
  arrivalDate: '2026-10-14',
  bookingHours: 24,
  refundConditions: 'Возврат доступен онлайн по правилам тарифа. Возможны удержания авиакомпании.',
  priceCheckedMinutesAgo: 5,
} as const

export const mockFlights: Flight[] = [
  { ...base, id: 'su-1883', airline: 'Аэрофлот', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Шереметьево SVO', departureTime: '06:20', arrivalTime: '08:55', durationMinutes: 275, stops: 0, baggage: true, priceRUB: 17840, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 4, recommended: true, departurePeriod: 'morning' },
  { ...base, id: 'y7-905', airline: 'Nordwind', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Шереметьево SVO', departureTime: '11:35', arrivalTime: '14:20', durationMinutes: 285, stops: 0, baggage: false, priceRUB: 14220, freeBooking: false, bookingHours: 0, refundable: false, refundConditions: 'Тариф невозвратный. Вернутся только предусмотренные правилами сборы.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 7, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 9 },
  { ...base, id: 'u6-1802', airline: 'Уральские авиалинии', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Домодедово DME', departureTime: '17:15', arrivalTime: '20:05', durationMinutes: 290, stops: 0, baggage: true, priceRUB: 19490, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный. Условия вынужденного возврата зависят от авиакомпании.', flexibleDate: true, kyrgyzCardsSupported: false, seatsLeft: 3, recommended: false, departurePeriod: 'evening', priceCheckedMinutesAgo: 12 },
  { ...base, id: 's7-3012', airline: 'S7 Airlines', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Домодедово DME', departureTime: '23:40', arrivalTime: '05:55', arrivalDate: '2026-10-15', durationMinutes: 495, stops: 1, baggage: true, priceRUB: 16980, freeBooking: false, bookingHours: 0, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 6, recommended: false, departurePeriod: 'night', priceCheckedMinutesAgo: 7, priceChanged: true },
  { ...base, id: 'kr-541', airline: 'Air Manas', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Внуково VKO', departureTime: '07:50', arrivalTime: '10:35', durationMinutes: 285, stops: 0, baggage: true, priceRUB: 15360, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный. Можно изменить дату с доплатой разницы в тарифе.', flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 5, recommended: true, departurePeriod: 'morning', priceCheckedMinutesAgo: 3 },
  { ...base, id: 'dp-958', airline: 'Победа', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Внуково VKO', departureTime: '09:10', arrivalTime: '12:05', durationMinutes: 295, stops: 0, baggage: false, priceRUB: 14590, freeBooking: false, bookingHours: 0, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: false, kyrgyzCardsSupported: false, seatsLeft: 2, recommended: false, departurePeriod: 'morning', priceCheckedMinutesAgo: 6 },
  { ...base, id: 'su-1885', airline: 'Аэрофлот', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Шереметьево SVO', departureTime: '13:40', arrivalTime: '16:20', durationMinutes: 280, stops: 0, baggage: true, priceRUB: 20750, freeBooking: true, bookingHours: 48, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 9, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 2 },
  { ...base, id: 'qh-771', airline: 'Avia Traffic Company', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Жуковский ZIA', departureTime: '15:25', arrivalTime: '18:20', durationMinutes: 295, stops: 0, baggage: true, priceRUB: 15110, freeBooking: false, bookingHours: 0, refundable: true, refundConditions: 'Возврат со сбором 3 000 ₽ до начала регистрации.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 6, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 11 },
  { ...base, id: 'a4-318', airline: 'Азимут', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Внуково VKO', departureTime: '12:05', arrivalTime: '19:40', durationMinutes: 515, stops: 1, baggage: false, priceRUB: 14380, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: true, kyrgyzCardsSupported: false, seatsLeft: 8, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 13 },
  { ...base, id: 'kr-547', airline: 'Air Manas', departureCity: 'Бишкек', arrivalCity: 'Москва', departureAirport: 'Манас FRU', arrivalAirport: 'Домодедово DME', departureTime: '20:30', arrivalTime: '23:20', durationMinutes: 290, stops: 0, baggage: true, priceRUB: 16240, freeBooking: true, refundable: true, flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 4, recommended: false, departurePeriod: 'evening', priceCheckedMinutesAgo: 5 },
  { ...base, id: 'su-1899', airline: 'Аэрофлот', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Шереметьево SVO', departureTime: '05:45', arrivalTime: '08:30', durationMinutes: 285, stops: 0, baggage: true, priceRUB: 18520, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 5, recommended: true, departurePeriod: 'morning', priceCheckedMinutesAgo: 4 },
  { ...base, id: 'dp-934', airline: 'Победа', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Внуково VKO', departureTime: '14:10', arrivalTime: '17:05', durationMinutes: 295, stops: 0, baggage: false, priceRUB: 13670, freeBooking: false, bookingHours: 0, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 2, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 10 },
  { ...base, id: 'kr-613', airline: 'Air Manas', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Внуково VKO', departureTime: '10:20', arrivalTime: '13:10', durationMinutes: 290, stops: 0, baggage: true, priceRUB: 15240, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный. Дату можно изменить с доплатой разницы.', flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 6, recommended: true, departurePeriod: 'morning', priceCheckedMinutesAgo: 7 },
  { ...base, id: 'u6-2906', airline: 'Уральские авиалинии', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Домодедово DME', departureTime: '18:45', arrivalTime: '21:40', durationMinutes: 295, stops: 0, baggage: true, priceRUB: 17130, freeBooking: false, bookingHours: 0, refundable: true, flexibleDate: true, kyrgyzCardsSupported: false, seatsLeft: 3, recommended: false, departurePeriod: 'evening', priceCheckedMinutesAgo: 9 },
  { ...base, id: 's7-3074', airline: 'S7 Airlines', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Домодедово DME', departureTime: '01:15', arrivalTime: '08:50', durationMinutes: 515, stops: 1, baggage: false, priceRUB: 14460, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 7, recommended: false, departurePeriod: 'night', priceCheckedMinutesAgo: 12 },
  { ...base, id: 'qh-705', airline: 'Avia Traffic Company', departureCity: 'Ош', arrivalCity: 'Москва', departureAirport: 'Ош OSS', arrivalAirport: 'Жуковский ZIA', departureTime: '12:55', arrivalTime: '15:55', durationMinutes: 300, stops: 0, baggage: true, priceRUB: 16080, freeBooking: true, bookingHours: 48, refundable: true, refundConditions: 'Возврат со сбором 2 500 ₽ до начала регистрации.', flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 5, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 4 },
  { ...base, id: 'u6-2810', airline: 'Уральские авиалинии', departureCity: 'Бишкек', arrivalCity: 'Краснодар', departureAirport: 'Манас FRU', arrivalAirport: 'Пашковский KRR', departureTime: '08:25', arrivalTime: '15:10', durationMinutes: 525, stops: 1, baggage: true, priceRUB: 21450, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 8, recommended: true, departurePeriod: 'morning', priceCheckedMinutesAgo: 6 },
  { ...base, id: 'a4-422', airline: 'Азимут', departureCity: 'Бишкек', arrivalCity: 'Краснодар', departureAirport: 'Манас FRU', arrivalAirport: 'Пашковский KRR', departureTime: '11:30', arrivalTime: '15:05', durationMinutes: 335, stops: 0, baggage: false, priceRUB: 22380, freeBooking: false, bookingHours: 0, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 3, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 10 },
  { ...base, id: 'su-1937', airline: 'Аэрофлот', departureCity: 'Бишкек', arrivalCity: 'Краснодар', departureAirport: 'Манас FRU', arrivalAirport: 'Пашковский KRR', departureTime: '06:10', arrivalTime: '13:45', durationMinutes: 515, stops: 1, baggage: true, priceRUB: 24960, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 9, recommended: false, departurePeriod: 'morning', priceCheckedMinutesAgo: 3 },
  { ...base, id: 's7-3218', airline: 'S7 Airlines', departureCity: 'Бишкек', arrivalCity: 'Краснодар', departureAirport: 'Манас FRU', arrivalAirport: 'Пашковский KRR', departureTime: '18:20', arrivalTime: '01:55', arrivalDate: '2026-10-15', durationMinutes: 515, stops: 1, baggage: true, priceRUB: 23170, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный. Дату можно изменить с доплатой.', flexibleDate: true, kyrgyzCardsSupported: false, seatsLeft: 5, recommended: false, departurePeriod: 'evening', priceCheckedMinutesAgo: 8 },
  { ...base, id: 'kr-629', airline: 'Air Manas', departureCity: 'Бишкек', arrivalCity: 'Краснодар', departureAirport: 'Манас FRU', arrivalAirport: 'Пашковский KRR', departureTime: '23:15', arrivalTime: '02:50', arrivalDate: '2026-10-15', durationMinutes: 335, stops: 0, baggage: true, priceRUB: 21980, freeBooking: false, bookingHours: 0, refundable: true, refundConditions: 'Возврат со сбором 3 500 ₽ до начала регистрации.', flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 4, recommended: false, departurePeriod: 'night', priceCheckedMinutesAgo: 15 },
  { ...base, id: 's7-3490', airline: 'S7 Airlines', departureCity: 'Бишкек', arrivalCity: 'Екатеринбург', departureAirport: 'Манас FRU', arrivalAirport: 'Кольцово SVX', departureTime: '19:35', arrivalTime: '22:35', durationMinutes: 180, stops: 0, baggage: true, priceRUB: 15890, freeBooking: false, bookingHours: 0, refundable: true, flexibleDate: false, kyrgyzCardsSupported: true, seatsLeft: 9, recommended: true, departurePeriod: 'evening', priceCheckedMinutesAgo: 8 },
  { ...base, id: 'n4-507', airline: 'Nordwind', departureCity: 'Бишкек', arrivalCity: 'Екатеринбург', departureAirport: 'Манас FRU', arrivalAirport: 'Кольцово SVX', departureTime: '02:40', arrivalTime: '10:25', durationMinutes: 465, stops: 1, baggage: false, priceRUB: 12990, freeBooking: true, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: true, kyrgyzCardsSupported: false, seatsLeft: 4, recommended: false, departurePeriod: 'night', priceCheckedMinutesAgo: 14 },
  { ...base, id: 'u6-2744', airline: 'Уральские авиалинии', departureCity: 'Бишкек', arrivalCity: 'Екатеринбург', departureAirport: 'Манас FRU', arrivalAirport: 'Кольцово SVX', departureTime: '07:05', arrivalTime: '10:00', durationMinutes: 175, stops: 0, baggage: true, priceRUB: 14720, freeBooking: true, refundable: true, flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 6, recommended: true, departurePeriod: 'morning', priceCheckedMinutesAgo: 4 },
  { ...base, id: 'kr-571', airline: 'Air Manas', departureCity: 'Бишкек', arrivalCity: 'Екатеринбург', departureAirport: 'Манас FRU', arrivalAirport: 'Кольцово SVX', departureTime: '13:15', arrivalTime: '16:10', durationMinutes: 175, stops: 0, baggage: false, priceRUB: 13480, freeBooking: false, bookingHours: 0, refundable: false, refundConditions: 'Тариф невозвратный.', flexibleDate: true, kyrgyzCardsSupported: true, seatsLeft: 3, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 9 },
  { ...base, id: 'su-1961', airline: 'Аэрофлот', departureCity: 'Бишкек', arrivalCity: 'Екатеринбург', departureAirport: 'Манас FRU', arrivalAirport: 'Кольцово SVX', departureTime: '10:40', arrivalTime: '17:55', durationMinutes: 435, stops: 1, baggage: true, priceRUB: 18310, freeBooking: true, bookingHours: 48, refundable: true, flexibleDate: false, kyrgyzCardsSupported: false, seatsLeft: 8, recommended: false, departurePeriod: 'day', priceCheckedMinutesAgo: 6 },
]

export const airlines = [...new Set(mockFlights.map((flight) => flight.airline))]
